### ISSUE TITLE
No websocket connection available

### ISSUE THREAD

**Issue by m19** [wunderlist/wunderlist.js#1]
Hey guys, really enjoying wunderlist. Was toying around with the API and noticed `wunderlistAPI.socket` doesn't work. It returns the error: `No websocket connection available`.

**Comment by octatone** [comment]
The sdk automatically manages the connection to the websocket.  Once you create an instance it will connect asynchronously and maintain the connection (reconnect if dropped, etc.).  You should always use the .getOutlet() method in the main Wunderlist class to return the currently available connection to the api (either socket or http).

https://github.com/wunderlist/wunderlist.js/blob/master/public/wunderlist/Wunderlist.js#L282
